OBJS-$(CONFIG_BWDIF_FILTER)                  += aarch64/vf_bwdif_init.o
OBJS-$(CONFIG_NLMEANS_FILTER)                += aarch64/vf_nlmeans_init.o
OBJS-$(CONFIG_YADIF_FILTER)                  += aarch64/vf_yadif_init.o

NEON-OBJS-$(CONFIG_BWDIF_FILTER)             += aarch64/vf_bwdif_neon.o
NEON-OBJS-$(CONFIG_NLMEANS_FILTER)           += aarch64/vf_nlmeans_neon.o
NEON-OBJS-$(CONFIG_YADIF_FILTER)             += aarch64/vf_yadif_neon.o
